# Generated by Django 3.1 on 2020-08-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
